# -*- coding: utf-8 -*-
"""ML2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ATDVg3cXkDOCdaZdoXi2YydbC_SKRvg
"""

from sklearn.datasets import load_iris

dir(load_iris())

iris_data=load_iris()

feature=iris_data.data

label=iris_data.target

from sklearn.model_selection import train_test_split

train_data,train_test,label_data,label_test=train_test_split(feature,label,test_size=0.3)

from sklearn.neighbors import KNeighborsClassifier

kclf=KNeighborsClassifier(n_neighbors=8)

trained=kclf.fit(train_data,label_data)

predicted=trained.predict(train_test)

from sklearn.metrics import accuracy_score

acc1=accuracy_score(label_test,predicted)
acc1

from sklearn.tree import DecisionTreeClassifier

dclf=DecisionTreeClassifier()

trained1=dclf.fit(train_data,label_data)

predict1=trained.predict(train_test)

acc2=accuracy_score(label_test,predict1)
acc2

import matplotlib.pyplot as plt
x=['KNN','Decision Tree']

y=[acc1,acc2]

plt.bar(x,y)

