# -*- coding: utf-8 -*-
"""ML4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19zbM1G8J2aJ29FzWz79J1YLHSH01zZST
"""

from sklearn.datasets import load_iris                          #  loading  iris  data set
from sklearn.neighbors import KNeighborsClassifier              #loading K-NN classifier
from sklearn.metrics import accuracy_score                      #loading function to calculate accuracy
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer                 #loading breast cancer dataset
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split            #  seperate data  into  training  and  testing

# loading  into a variable
iris_data=load_iris() 

#   data with  attributes 
feature_iris=iris_data.data

#  extracting  lable as per  features
label_iris=iris_data.target

#sepearting data into four parts---test size is 30% 
train_data1,train_test1,label_data1,label_test1=train_test_split(feature_iris,label_iris,test_size=0.3)

#calling K-nearest neighbor classifier with k=7
kclf1=KNeighborsClassifier(n_neighbors=7)

# applying  training  data for k-nn 
trained1=kclf1.fit(train_data1,label_data1)

#now time for  prediction for k-nn
predicted1=trained1.predict(train_test1)

#calculating accuracy score of K-NN
acc1=accuracy_score(label_test1,predicted1)

#calling decision tree classifier
dclf1=DecisionTreeClassifier()

# applying  training  data for dec_tree
trained2=dclf1.fit(train_data1,label_data1)

#now time for  prediction for decision tree
predict2=trained2.predict(train_test1)

#calculating accuracy score of decision tree
acc2=accuracy_score(label_test1,predict2)

print('Accuracy  score of K-NN for iris:',acc1)
print('Accuracy score of decision tree for iris:',acc2)
print('Accuracy score of decision tree for breast cancer:',acc3)
print('Accuracy score of K-NN for breast cancer:',acc4)


#loading canser data into a variable
cancer=load_breast_cancer()

#cancer data attributes
cancer_data=cancer.data

#answers/labels...which are exactly same in number as features
labels=cancer.target

train_data2,train_test2,label_data2,label_test2=train_test_split(cancer_data,labels,test_size=0.3)

clf2=DecisionTreeClassifier()

trained3=clf2.fit(train_data2,label_data2)

predicted3=trained3.predict(train_test2)

acc3=accuracy_score(label_test2,predicted3)

kcnf2=KNeighborsClassifier(n_neighbors=7)

trained4=kcnf2.fit(train_data2,label_data2)

predicted4=trained4.predict(train_test2)

acc4=accuracy_score(label_test2,predicted4)



#Pie chart for the comparison of actual score of iris and breast datasets under knn and decision tree classifier
x=[acc1,acc2,acc3,acc4]
y=['K-NN for iris','Decision_tree for iris','Decision_tree for cancer','K-NN for cancer']
plt.pie(x,labels=y,autopct='%1.1f%%')
plt.show()





